all:
	gcc main.c employes/employes.c employes/employes.h Capteurs/capteur.c Capteurs/capteur.h ouvrier/ouvrier.c ouvrier/ouvrier.h equipements/fonction-BM.c equipements/fonction-BM.h clients/client.c clients/client.h troupeau/troupeau.h troupeau/troupeau.c -o run
